module_name: "example_sensor_hub"

buckets:
    bucket_0:
        # NOTE: frequency will be converted to an integer number of ms for a delay
        frequency_hz: 250
        parameters:
            # these must directly be a variable defined in GopherCAN
            front1SuspensionLoadCell_V:
                ADC: ADC1_IN11 # Connector 2 - FLR
                sensor:  full_raw_voltage_sensor # suspension_load_cell
                samples_buffered: 2
            front2SuspensionLoadCell_V:
                ADC: ADC1_IN12 # Connector 3 - FLF
                sensor:  full_raw_voltage_sensor # suspension_load_cell
                samples_buffered: 2
            front3SuspensionLoadCell_V:
                ADC: ADC1_IN13 # Connector 1 - FUR
                sensor:  full_raw_voltage_sensor # suspension_load_cell
                samples_buffered: 2
            front4SuspensionLoadCell_V:
                ADC: ADC1_IN10 # Connector 6 - FP
                sensor:  full_raw_voltage_sensor # suspension_load_cell
                samples_buffered: 2
            front5SuspensionLoadCell_V:
                ADC: ADC1_IN15 # Connector 5 - FUF
                sensor:  full_raw_voltage_sensor # suspension_load_cell
                samples_buffered: 2
            front6SuspensionLoadCell_V:
                ADC: ADC1_IN7 # Connector 4 - FS
                sensor:  full_raw_voltage_sensor # suspension_load_cell
                samples_buffered: 2