
module_name: "example_sensor_hub"

buckets:
    bucket_0:
        # NOTE: frequency will be converted to an integer number of ms for a delay
        frequency_hz: 250
        parameters:
            # these must directly be a variable defined in GopherCAN
            waterTempBeforeOil_C:
                ADC: ADC1_IN11
                sensor: temp_sensor
                samples_buffered: 2
                
            waterTempAfterOil_C:
                ADC: ADC1_IN12
                sensor: temp_sensor
                samples_buffered: 2
                
            waterTempBeforeHeatExchanger_C:
                ADC: ADC1_IN13
                sensor: temp_sensor
                samples_buffered: 2

            waterTempAfterHeatExchanger_C:
                ADC: ADC1_IN10
                sensor: temp_sensor
                samples_buffered: 2

