
module_name: "example_sensor_hub"

buckets:
    bucket_0:
        # NOTE: frequency will be converted to an integer number of ms for a delay
        frequency_hz: 100
        parameters:
            # Listed in order of their pins in the sensor hub board side connector
            airLinePressure_psi:
                ADC: ADC1_IN11
                sensor: pressure_sensor_sealed_gauge
                samples_buffered: 2
            airTankPressure_psi:
                ADC: ADC1_IN12
                sensor: air_tank_pressure_sensor
                samples_buffered: 2
            manifoldTemp_C:
                ADC: ADC1_IN13
                sensor: combined_temp_sensor
                samples_buffered: 2
            manifoldPressure_kPa:
                ADC: ADC1_IN10
                sensor: combined_pressure_sensor
                samples_buffered: 2
            shockPosRearRight_mm:
                ADC: ADC1_IN15
                sensor: linear_pos_sensor_50
                samples_buffered: 2
            rightAuxTemp_C:
                ADC: ADC1_IN7
                sensor: temp_sensor
                samples_buffered: 2
            # rightShroudPitot_inH2O:
            #     ADC: ADC1_IN6
            #     sensor: differential_pressure_sensor
            #     samples_buffered: 2
            brakeTempRearRight_C:
                ADC: ADC1_IN6
                sensor: brake_temp_sensor
                samples_buffered: 2
            wheelSpeedRearRight_mph:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 2
            # rightFlowRate_LPerMin:
            #     ADC: NON_ADC
            #     sensor: NON_ADC
            #     samples_buffered: 2