module_name: "example_sensor_hub"

buckets:
    bucket_0:
        # NOTE: frequency will be converted to an integer number of ms for a delay
        frequency_hz: 100
        parameters:
            # these must directly be a variable defined in GopherCAN
            rear1SuspensionLoadCell_V:
                ADC: ADC1_IN11 # Connector 4 - RUF
                sensor: full_raw_voltage_sensor # suspension_load_cell
                samples_buffered: 2
            rear2SuspensionLoadCell_V:
                ADC: ADC1_IN12 # Connector 2 - RLR
                sensor: full_raw_voltage_sensor # suspension_load_cell
                samples_buffered: 2
            rear3SuspensionLoadCell_V:
                ADC: ADC1_IN13 # Connector 3 - RLF
                sensor: full_raw_voltage_sensor # suspension_load_cell
                samples_buffered: 2
            rear4SuspensionLoadCell_V:
                ADC: ADC1_IN10 # Connector 7 - RUR
                sensor: full_raw_voltage_sensor # suspension_load_cell
                samples_buffered: 2
            rear5SuspensionLoadCell_V:
                ADC: ADC1_IN15
                sensor: full_raw_voltage_sensor # suspension_load_cell
                samples_buffered: 2
            rear6SuspensionLoadCell_V:
                ADC: ADC1_IN7
                sensor: full_raw_voltage_sensor # suspension_load_cell
                samples_buffered: 2