module_name: "example_sensor_hub"

buckets:
    bucket_0:
        # NOTE: frequency will be converted to an integer number of ms for a delay
        frequency_hz: 250
        parameters:
            # these must directly be a variable defined in GopherCAN
            rear1SuspensionLoadCell_N:
                ADC: ADC1_IN11
                sensor: suspension_load_cell
                samples_buffered: 2
            rear2SuspensionLoadCell_N:
                ADC: ADC1_IN12
                sensor: suspension_load_cell
                samples_buffered: 2
            rear3SuspensionLoadCell_N:
                ADC: ADC1_IN13
                sensor: suspension_load_cell
                samples_buffered: 2
            rear4SuspensionLoadCell_N:
                ADC: ADC1_IN10
                sensor: suspension_load_cell
                samples_buffered: 2
            rear5SuspensionLoadCell_N:
                ADC: ADC1_IN15
                sensor: suspension_load_cell
                samples_buffered: 2
            rear6SuspensionLoadCell_N:
                ADC: ADC1_IN7
                sensor: suspension_load_cell
                samples_buffered: 2