
module_name: "example_sensor_hub"

buckets:
    bucket_0:
        frequency_hz: 100
        parameters:
            # Listed in order of their pins in the sensor hub board side connector
            shockPosRearLeft_mm:
                ADC: ADC1_IN11
                sensor: linear_pos_sensor_50
                samples_buffered: 2
            shockPosRearRight_mm:
                ADC: ADC1_IN12
                sensor: linear_pos_sensor_50
                samples_buffered: 2
            wheelSpeedRearLeft_mph:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 2
            wheelSpeedRearRight_mph:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 2

