
module_name: "example_sensor_hub"

buckets:
    bucket_0:
        # NOTE: frequency will be converted to an integer number of ms for a delay
        frequency_hz: 100
        parameters:
            # these must directly be a variable defined in GopherCAN
            # Listed in order of their pins in the sensor hub board side connector
            exhaustTemp_C:
                ADC: ADC1_IN11
                sensor: exhaust_temp_sensor
                samples_buffered: 2
            shockPosRearLeft_mm:
                ADC: ADC1_IN12
                sensor: linear_pos_sensor_50
                samples_buffered: 2
            leftRadWaterTempIn_C:
                ADC: ADC1_IN13
                sensor: temp_sensor
                samples_buffered: 2
            leftRadWaterTempOut_C:
                ADC: ADC1_IN10
                sensor: temp_sensor
                samples_buffered: 2
            fuelPressure_psi:
                ADC: ADC1_IN15
                sensor: pressure_sensor_absolute
                samples_buffered: 2
            wheelSpeedRearLeft_mph:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 2

