
module_name: "example_sensor_hub"

buckets:
    bucket_0:
        frequency_hz: 100
        parameters:
            dam_chan_4:
                ADC: ADC1_IN10
                sensor: linear_pos_sensor_50
                samples_buffered: 2
                
            dam_chan_5:
                ADC: ADC2_IN12
                sensor: linear_pos_sensor_50
                samples_buffered: 2
                
            dam_chan_6:
                ADC: ADC2_IN7
                sensor: linear_pos_sensor_50
                samples_buffered: 2

